### PR TITLE
Broken login

### PR DESCRIPTION
**Pull request by ghost**
- auth.login method signature change
- auth config property used for extracting authToken from response added

### CODE REVIEW

**Comment by doktordirk** [comment]
ps: you have any more ideas/ problems, please don't hesitate.

**Comment by ghost** [comment]
switching to use multiple shells would be a good example; http://davismj.me/blog/aurelia-login-best-practices-pt-1/
though i am looking to implement that self, once I'm done i can submit a pull request if you're interested

**Comment by doktordirk** [comment]
not sure how much it actually adds. still, a sample would be good. i think i should make several sample repos anyhow

**Comment by ghost** [comment]
having looked at it further i agree with you, the multiple shells would be a different sample, not adding to the current one

**Pull request merged**
